spring:
  application:
    name: sysflow-backend
  datasource:
    url: jdbc:postgresql://ep-blue-dew-azwsyfoz-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_0LipC8vdxMmY
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:change-me-in-env-this-is-a-dev-only-default-secret-value}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

gemini:
  api-key: ${GEMINI_API_KEY:}
