import type { ComponentType } from '../components/nodes'

interface GraphNodeLike {
  id: string
  type: string
  label?: string
  config?: Record<string, unknown>
}

interface GraphEdgeLike {
  source: string
  target: string
}

interface ServiceSpec {
  /** 'image' pulls a real off-the-shelf image; 'build' means "you write the Dockerfile" — resolved to ./<serviceName> at generation time. */
  directive: 'image' | 'build'
  value?: string
  buildNote?: string
  ports?: string[]
  environment?: Record<string, string>
  volumes?: string[]
}

/**
 * Best-effort docker-compose service per component type — a starting point to edit, not a
 * production-ready deployment. Types with no sensible self-hosted equivalent (managed services,
 * client-side code, external providers, or things that aren't a single container) are called
 * out as comments instead of a service block — see MANAGED_ONLY_NOTE.
 */
const SERVICE_SPECS: Partial<Record<ComponentType, ServiceSpec>> = {
  loadBalancer: { directive: 'image', value: 'nginx:1.27-alpine', ports: ['80:80'] },
  apiGateway: { directive: 'image', value: 'nginx:1.27-alpine', ports: ['8000:80'] },
  waf: { directive: 'image', value: 'owasp/modsecurity-crs:nginx' },
  ingress: { directive: 'image', value: 'nginx:1.27-alpine' },
  service: { directive: 'build', buildNote: 'your application code — add a Dockerfile here' },
  worker: { directive: 'build', buildNote: 'your background worker code — add a Dockerfile here' },
  serverless: { directive: 'build', buildNote: 'your function code — most serverless platforms don\'t run from compose; this is a local stand-in' },
  cronJob: { directive: 'build', buildNote: 'your scheduled job code — add a Dockerfile and your own cron/scheduler entrypoint' },
  autoScalingGroup: { directive: 'build', buildNote: 'your application code — add "deploy: replicas: N" (swarm) or move to k8s for real autoscaling' },
  queue: { directive: 'image', value: 'rabbitmq:3-management-alpine', ports: ['5672:5672', '15672:15672'] },
  messageBroker: { directive: 'image', value: 'bitnami/kafka:3.7', ports: ['9092:9092'], environment: { KAFKA_CFG_NODE_ID: '0', KAFKA_CFG_PROCESS_ROLES: 'controller,broker' } },
  eventBus: { directive: 'image', value: 'nats:2.10-alpine', ports: ['4222:4222'] },
  cache: { directive: 'image', value: 'redis:7-alpine', ports: ['6379:6379'] },
  database: { directive: 'image', value: 'postgres:16-alpine', ports: ['5432:5432'], environment: { POSTGRES_PASSWORD: 'change-me' }, volumes: ['pgdata:/var/lib/postgresql/data'] },
  searchIndex: { directive: 'image', value: 'opensearchproject/opensearch:2', ports: ['9200:9200'], environment: { 'discovery.type': 'single-node' } },
  objectStorage: { directive: 'image', value: 'minio/minio:latest', ports: ['9000:9000', '9001:9001'], environment: { MINIO_ROOT_USER: 'minioadmin', MINIO_ROOT_PASSWORD: 'change-me' }, volumes: ['objectdata:/data'] },
  monitoring: { directive: 'image', value: 'prom/prometheus:latest', ports: ['9090:9090'] },
  logging: { directive: 'image', value: 'grafana/loki:latest', ports: ['3100:3100'] },
}

const MANAGED_ONLY_NOTE: Partial<Record<ComponentType, string>> = {
  client: 'runs on the end user\'s device — not a backend service',
  mobile: 'runs on the end user\'s device — not a backend service',
  webBrowser: 'runs on the end user\'s device — not a backend service',
  iotDevice: 'runs on external hardware — not a backend service',
  dns: 'typically your registrar/DNS provider — not self-hosted',
  cdn: 'typically a managed CDN (Cloudflare/CloudFront) — not self-hosted here',
  containerOrchestrator: 'this IS the orchestrator (k8s/ECS/Swarm) — not something you run inside compose',
  dataWarehouse: 'typically a managed warehouse (BigQuery/Snowflake/Redshift) — not self-hosted here',
  dataLake: 'typically managed object storage + a catalog (S3+Glue, etc.) — not self-hosted here',
  webhook: 'an inbound endpoint on one of your services — add a route, not a separate container',
  thirdPartyApi: 'an external provider you call — nothing to deploy',
  paymentGateway: 'an external provider (Stripe/etc.) — nothing to deploy',
}

function sanitizeServiceName(id: string): string {
  const cleaned = id.toLowerCase().replace(/[^a-z0-9_-]/g, '_')
  return /^[a-z]/.test(cleaned) ? cleaned : `svc_${cleaned}`
}

export function generateDockerCompose(nodes: GraphNodeLike[], edges: GraphEdgeLike[]): string {
  const deployable = nodes.filter((n) => SERVICE_SPECS[n.type as ComponentType])
  const deployableIds = new Set(deployable.map((n) => n.id))
  const skipped = nodes.filter((n) => !deployable.includes(n))

  const lines: string[] = [
    '# Generated by SysFlow from your architecture diagram — a STARTING POINT, not a deployable',
    '# production stack. Placeholder images, secrets, and volumes all need real values.',
    '',
  ]

  if (skipped.length > 0) {
    lines.push('# Not included as containers:')
    for (const n of skipped) {
      const note = MANAGED_ONLY_NOTE[n.type as ComponentType] ?? 'no self-hosted equivalent mapped for this component type'
      lines.push(`#   - ${n.label ?? n.id} (${n.type}): ${note}`)
    }
    lines.push('')
  }

  lines.push('services:')
  const volumeNames = new Set<string>()

  for (const node of deployable) {
    const spec = SERVICE_SPECS[node.type as ComponentType]!
    const serviceName = sanitizeServiceName(node.id)
    const dependsOn = edges
      .filter((e) => e.target === node.id && deployableIds.has(e.source))
      .map((e) => sanitizeServiceName(e.source))

    if (spec.directive === 'build') {
      lines.push(`  # ${spec.buildNote}`)
      lines.push(`  ${serviceName}:`)
      lines.push(`    build: ./${serviceName}`)
    } else {
      lines.push(`  ${serviceName}:`)
      lines.push(`    image: ${spec.value}`)
    }
    if (spec.ports?.length) {
      lines.push('    ports:')
      for (const port of spec.ports) lines.push(`      - "${port}"`)
    }
    if (spec.environment && Object.keys(spec.environment).length > 0) {
      lines.push('    environment:')
      for (const [key, value] of Object.entries(spec.environment)) lines.push(`      ${key}: "${value}"`)
    }
    if (spec.volumes?.length) {
      lines.push('    volumes:')
      for (const volume of spec.volumes) {
        lines.push(`      - ${volume}`)
        volumeNames.add(volume.split(':')[0])
      }
    }
    if (dependsOn.length > 0) {
      lines.push('    depends_on:')
      for (const dep of dependsOn) lines.push(`      - ${dep}`)
    }
    lines.push('')
  }

  if (volumeNames.size > 0) {
    lines.push('volumes:')
    for (const name of volumeNames) lines.push(`  ${name}:`)
  }

  return lines.join('\n')
}
